add_project:
  dec: "主流程"
  parameters:
    -
      test_name: '添加项目-主流程'
      mode: 1
      type: json
      methods: post
      url: /opservice/project/add
      data: {
        'name': 'xuejian_项目',
        'desc': '测试',
        'projectTypeId': '1'
      }
      parser:   &parser {'code' :"['code']", 'msg': '["msg"]' }
      expected: &expected { 'code': 1000, 'msg': '成功' }

getProjectListByCondition:
  dec: "主流程"
  parameters:
    -
      test_name: '根据项目分类id和名称获取项目列表-项目分类id查询'
      mode: 0
      type: json
      methods: get
      url: /opservice/project/getProjectListByCondition
      data: {
        'cateGoryId': 1,
        'name': ''
      }
      parser:   *parser
      expected: *expected
    -
      test_name: '根据项目分类id和名称获取项目列表-项目名称查询'
      mode: 0
      type: json
      methods: get
      url: /opservice/project/getProjectListByCondition
      data: {
        'name': 'xuejian_项目分类',
        'cateGoryId': ''
      }
      parser:   *parser
      expected: *expected

add_projectType:
  dec: "主流程"
  parameters:
    -
      test_name: '添加项目分类-主流程'
      mode: 1
      type: json
      methods: get
      url: /opservice/projectType/add
      data: {
        'name': 'xuejian_项目分类',
        'desc': '测试'
      }
      parser:   *parser
      expected: *expected

getProjectTypes:
  dec: "主流程"
  parameters:
    -
      test_name: '获取项目分类列表-主流程'
      mode: 0
      type: json
      methods: get
      url: /opservice/projectType/getProjectTypes
      data: {
      }
      parser:   *parser
      expected: *expected

getProjectTypeByName:
  dec: "主流程"
  parameters:
    -
      test_name: '根据项目分类名称查询项目分类信息-主流程'
      mode: 0
      type: json
      methods: get
      url: /opservice/projectType/getProjectTypeByName
      data: {
              'name': 'xuejian_项目分类'
      }
      parser:   *parser
      expected: *expected

add_property:
  dec: "主流程"
  parameters:
    -
      test_name: '新增动态属性-主流程'
      mode: 1
      type: json
      methods: post
      url: /opservice/property/add
      data: {
        'name': 'xuejian_属性',
        'projectId': 1,
        'description': '测试',
        'isMust': 0,
        'isMulti': 0
      }
      parser:   *parser
      expected: *expected
    -
      test_name: '新增动态属性-名称重复'
      mode: 1
      type: json
      methods: post
      url: /opservice/property/add
      data: {
        'name': 'xuejian_属性001',
        'projectId': 1,
        'description': '测试',
        'isMust': 0,
        'isMulti': 0
      }
      parser:    {'code' :"['code']", 'msg': '["msg"]' }
      expected:  { 'code': 10002, 'msg': '名称不可重复' }


edit_property:
  dec: "主流程"
  parameters:
    -
      test_name: '编辑动态属性-主流程'
      mode: 1
      type: json
      methods: post
      url: /opservice/property/edit
      data: {
        'id': 10,
        'name': 'xuejian_属性001',
        'projectId': 1,
        'description': '测试',
        'isMust': 0,
        'isMulti': 0
      }
      parser:   *parser
      expected: *expected

get_Search:
  dec: "主流程"
  parameters:
    -
      test_name: '查询动态属性-主流程'
      mode: 0
      type: json
      methods: get
      url: /opservice/property/search
      data: {
        'propertyName': '',
        'projectId': '',
        'moduleId': ''
      }
      parser:   *parser
      expected: *expected
    -
      test_name: '查询动态属性-项目id查询'
      mode: 0
      type: json
      methods: get
      url: /opservice/property/search
      data: {
        'propertyName': '',
        'projectId': 1,
        'moduleId': ''
      }
      parser:   *parser
      expected: *expected
    -
      test_name: '查询动态属性-模块id查询'
      mode: 0
      type: json
      methods: get
      url: /opservice/property/search
      data: {
        'propertyName': '',
        'projectId': '',
        'moduleId': 1
      }
      parser:   *parser
      expected: *expected
    -
      test_name: '查询动态属性-属性名称(String)查询'
      mode: 0
      type: json
      methods: get
      url: /opservice/property/search
      data: {
        'propertyName': '测试',
        'projectId': '',
        'moduleId': ''
      }
      parser:   *parser
      expected: *expected
getOne:
  dec: "主流程"
  parameters:
    -
      test_name: '获取一条动态属性的基本信息-主流程'
      mode: 0
      type: json
      methods: get
      url: /opservice/property/getOne
      data: {
        'propertyId': 10
      }
      parser:   *parser
      expected: *expected

searchModule:
  dec: "主流程"
  parameters:
    -
      test_name: '搜索模块-主流程'
      mode: 0
      type: json
      methods: get
      url: /opservice/property/searchModule
      data: {
        'name': '课程'
      }
      parser:   *parser
      expected: *expected

add_property_field:
  dec: "主流程"
  parameters:
    -
      test_name: '新增属性字段-主流程'
      mode: 1
      type: json
      methods: post
      url: /opservice/propertyfield/add
      data: {
        'propertyNameId': 10,
        'description': '测试',
        'filedName': 'xuejian_字段'
      }
      parser:   *parser
      expected: *expected

edit_property_field:
  dec: "主流程"
  parameters:
    -
      test_name: '编辑属性字段-主流程'
      mode: 1
      type: json
      methods: post
      url: /opservice/propertyfield/edit
      data: {
        'id': 12,
        'propertyNameId': 10,
        'description': '测试',
        'filedName': 'xuejian_字段'
      }
      parser:   *parser
      expected: *expected

get_property_field:
  dec: "主流程"
  parameters:
    -
      test_name: '查询属性字段-主流程'
      mode: 0
      type: json
      methods: get
      url: /opservice/propertyfield/search
      data: {
        'propertyNameId': 12,
        'fieldName': 'xuejian'
      }
      parser:   *parser
      expected: *expected

getOne_property_field:
  dec: "主流程"
  parameters:
    -
      test_name: '查询属性字段-主流程'
      mode: 0
      type: json
      methods: get
      url: /opservice/propertyfield/getOne
      data: {
        'id': 12
      }
      parser:   *parser
      expected: *expected
